# Generated by Django 5.2.8 on 2026-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
