# Generated by Django 5.2.8 on 2026-01-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "User_portefolio",
            "0002_alter_utilisateur_age_alter_utilisateur_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="image",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="projet",
            name="lien",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="reseausocial",
            name="lien",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="age",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="lien_cv",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
