# Generated by Django 5.2.8 on 2026-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0003_alter_projet_image_alter_projet_lien_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="photo_profil",
            field=models.TextField(),
        ),
    ]
