# Generated by Django 5.2.8 on 2026-01-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0004_alter_utilisateur_photo_profil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projets_images/"),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="photo_profil",
            field=models.ImageField(blank=True, null=True, upload_to="photos_profils/"),
        ),
    ]
