# Generated by Django 5.2.8 on 2026-01-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0005_alter_projet_image_alter_utilisateur_photo_profil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="photo_profil",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
