# Generated by Django 5.2.8 on 2026-01-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0006_alter_utilisateur_photo_profil"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="type_de_projet",
            field=models.CharField(
                choices=[("MOBILE", "Mobile"), ("WEB", "Web")],
                default="WEB",
                max_length=50,
            ),
        ),
    ]
