# Generated by Django 5.2.8 on 2026-01-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0007_projet_type_de_projet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="projet",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="projets", to="User_portefolio.language"
            ),
        ),
    ]
