# Generated by Django 5.2.8 on 2026-03-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User_portefolio", "0008_language_projet_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("LANGAGE_PROGRAMMATION", "Langage de Programmation"),
                            ("FRAMEWORK", "Framework"),
                            ("LOGICIEL", "Logiciel"),
                            ("BASE_DONNEES", "Base de Données"),
                            ("OUTIL", "Outil"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("DEBUTANT", "Débutant"),
                            ("INTERMEDIAIRE", "Intermédiaire"),
                            ("AVANCE", "Avancé"),
                            ("EXPERT", "Expert"),
                        ],
                        default="INTERMEDIAIRE",
                        max_length=50,
                    ),
                ),
                ("icone_url", models.URLField(blank=True, max_length=500, null=True)),
                ("date_acquisition", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["categorie", "nom"],
            },
        ),
        migrations.AddField(
            model_name="projet",
            name="competences",
            field=models.ManyToManyField(
                blank=True, related_name="projets", to="User_portefolio.competence"
            ),
        ),
    ]
